### Deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    component: frontend
    project: roboshop
    tier: app
spec:
  selector:
    matchLabels:
      component: frontend
      project: roboshop
      tier: app
  replicas: 2
  ### This is Pod definiton
  template:
    metadata:
      name: frontend
      labels:
        component: frontend
        project: roboshop
        tier: app
    spec:
      containers:
      - name: frontend
        image: {{ .Values.deployment.imageURL }}:{{ .Values.deployment.imageVersion }}
        #command: ["sh", "-c", "echo 'failure' && exit 1"]
        envFrom:
        - configMapRef:
            name: frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi