apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: frontend
  namespace: roboshop
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  serviceRef: 
    name: frontend
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:us-east-1:025523569021:loadbalancer/app/roboshop-dev-ingress-alb/3c9db58fb1ffad78
